// ============ API ENDPOINTS ============

export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login/',
    REGISTER: '/auth/register/',
    LOGOUT: '/auth/logout/',
    REFRESH: '/auth/refresh/',
    ME: '/auth/me/',
    PROFILE: '/auth/profile/',
    CHANGE_PASSWORD: '/auth/change-password/',
    PASSWORD_RESET_REQUEST: '/auth/password-reset/request/',
    PASSWORD_RESET_CONFIRM: '/auth/password-reset/confirm/',
    VERIFY_EMAIL: '/auth/verify-email/',
    RESEND_VERIFICATION: '/auth/resend-verification/',
    PREFERENCES: '/auth/preferences/',
    ADDRESSES: '/auth/addresses/',
    ADDRESS_DETAIL: (id: string) => `/auth/addresses/${id}/`,
    ADDRESS_SET_DEFAULT: (id: string) => `/auth/addresses/${id}/set-default/`,
    STATS: '/auth/stats/',
    ACTIVITIES: '/auth/activities/',
    AGENT_STATUS: '/auth/agent/status/',
    AGENT_LOCATION: '/auth/agent/location/',
    AGENT_STATS: '/auth/agent/stats/',
    ADVISOR_STATUS: '/auth/advisor/status/',
    ADVISOR_STATS: '/auth/advisor/stats/',
  },
  PRODUCTS: {
    LIST: '/products/',
    DETAIL: (slug: string) => `/products/${slug}/`,
    DETAIL_BY_ID: (id: string) => `/products/${id}/`,
    SEARCH: '/products/search/',
    CATEGORIES: '/products/categories/',
    CATEGORY_TREE: '/products/categories/tree/',
    CATEGORY_DETAIL: (slug: string) => `/products/categories/${slug}/`,
    CATEGORY_PRODUCTS: (slug: string) => `/products/categories/${slug}/products/`,
    FEATURED: '/products/featured/',
    POPULAR: '/products/popular/',
    NEW: '/products/new/',
    ON_SALE: '/products/on-sale/',
    COMPARE: '/products/compare/',
    REVIEWS: (id: string) => `/products/${id}/reviews/`,
    REVIEW_DETAIL: (id: string) => `/products/reviews/${id}/`,
    REVIEW_HELPFUL: (id: string) => `/products/reviews/${id}/helpful/`,
    AVAILABILITY: (id: string) => `/products/${id}/availability/`,
    RELATED: (id: string) => `/products/${id}/related/`,
    BRAND: (brand: string) => `/products/brand/${brand}/`,
    PRICE_HISTORY: (id: string) => `/products/${id}/price-history/`,
    VARIANTS: (id: string) => `/products/${id}/variants/`,
    VARIANT_BY_SKU: (sku: string) => `/products/variants/sku/${sku}/`,
    TAGS: '/products/tags/',
    TAG_PRODUCTS: (slug: string) => `/products/tags/${slug}/`,
    ADMIN: '/products/admin/',
    ADMIN_DETAIL: (id: string) => `/products/admin/${id}/`,
    ADMIN_STOCK: (id: string) => `/products/admin/${id}/stock/`,
    ADMIN_BULK: '/products/admin/bulk/',
    ADMIN_IMAGES: (id: string) => `/products/admin/${id}/images/`,
    ADMIN_IMAGE_DELETE: (id: string) => `/products/admin/images/${id}/`,
    ADMIN_CATEGORIES: '/products/admin/categories/',
    ADMIN_CATEGORY_DETAIL: (id: string) => `/products/admin/categories/${id}/`,
    ADMIN_TAGS: '/products/admin/tags/',
    ADMIN_TAG_DELETE: (id: string) => `/products/admin/tags/${id}/`,
    ADMIN_IMPORT: '/products/admin/import/',
    ADMIN_EXPORT: '/products/admin/export/',
  },
  EXTERNAL_PRODUCTS: {
    LIST: '/external-products/',
    CREATE: '/external-products/',
    DETAIL: (id: string) => `/external-products/${id}/`,
    RETRY: (id: string) => `/external-products/${id}/retry/`,
  },
  CART: {
    BASE: '/cart/',
    SUMMARY: '/cart/summary/',
    COUNT: '/cart/count/',
    TOTAL: '/cart/total/',
    VALIDATE: '/cart/validate/',
    ITEMS: '/cart/items/',
    ITEM_DETAIL: (id: string) => `/cart/items/${id}/`,
    ITEMS_BATCH: '/cart/items/batch/',
    ITEMS_REMOVE_BATCH: '/cart/items/batch/remove/',
    SELECT_ITEMS: '/cart/select-items/',
    SELECT_ALL: '/cart/select-all/',
    SAVE_FOR_LATER: (id: string) => `/cart/items/${id}/save-for-later/`,
    MOVE_TO_CART: (id: string) => `/cart/items/${id}/move-to-cart/`,
    SAVED: '/cart/saved/',
    APPLY_COUPON: '/cart/apply-coupon/',
    REMOVE_COUPON: '/cart/coupon/',
    COUPON_DETAIL: (code: string) => `/cart/coupon/${code}/`,
    COUPONS_AVAILABLE: '/cart/coupons/available/',
    ESTIMATE_SHIPPING: '/cart/estimate-shipping/',
    SHIPPING_OPTIONS: '/cart/shipping-options/',
    SELECT_SHIPPING: '/cart/select-shipping/',
    MERGE: '/cart/merge/',
    GUEST_ID: '/cart/guest-id/',
    SAVE: '/cart/save/',
    LOAD: '/cart/load/',
    SYNC: '/cart/sync/',
    STATISTICS: '/cart/statistics/',
    WISHLIST: '/cart/wishlist/',
    WISHLIST_ITEM: (id: string) => `/cart/wishlist/${id}/`,
    WISHLIST_CHECK: (id: string) => `/cart/wishlist/check/${id}/`,
  },
  ORDERS: {
    LIST: '/orders/',
    DETAIL: (id: string) => `/orders/${id}/`,
    REFERENCE: (ref: string) => `/orders/reference/${ref}/`,
    CREATE: '/orders/',
    CANCEL: (id: string) => `/orders/${id}/cancel/`,
    STATUS: (id: string) => `/orders/${id}/status/`,
    HISTORY: (id: string) => `/orders/${id}/history/`,
    TIMELINE: (id: string) => `/orders/${id}/timeline/`,
    ITEMS: (id: string) => `/orders/${id}/items/`,
    ITEM_DETAIL: (id: string, itemId: string) => `/orders/${id}/items/${itemId}/`,
    INVOICE: (id: string) => `/orders/${id}/invoice/`,
    INVOICE_DOWNLOAD: (id: string) => `/orders/${id}/invoice/download/`,
    INVOICES: '/orders/invoices/',
    SUMMARY: '/orders/summary/',
    STATS: '/orders/stats/',
    RETURNS: (id: string) => `/orders/${id}/returns/`,
    RETURN_DETAIL: (id: string) => `/orders/returns/${id}/`,
    RETURN_STATUS: (id: string) => `/orders/returns/${id}/status/`,
    RETURN_CANCEL: (id: string) => `/orders/returns/${id}/cancel/`,
    REFUNDS: (id: string) => `/orders/${id}/refunds/`,
    REFUND_DETAIL: (id: string) => `/orders/refunds/${id}/`,
    SHIPMENT: (id: string) => `/orders/${id}/shipment/`,
    TRACKING: (number: string) => `/orders/tracking/${number}/`,
    TRACKING_HISTORY: (number: string) => `/orders/tracking/${number}/history/`,
    ADMIN_ALL: '/orders/admin/all/',
    ADMIN_ASSIGN: (id: string) => `/orders/admin/${id}/assign-delivery/`,
    ADMIN_UPDATE: (id: string) => `/orders/admin/${id}/`,
    ADMIN_DELETE: (id: string) => `/orders/admin/${id}/`,
    ADMIN_RETURN_APPROVE: (id: string) => `/orders/admin/returns/${id}/approve/`,
    ADMIN_RETURN_REJECT: (id: string) => `/orders/admin/returns/${id}/reject/`,
    ADMIN_REFUND_PROCESS: (id: string) => `/orders/admin/refunds/${id}/process/`,
    ADMIN_ANALYTICS: '/orders/admin/analytics/',
    ADMIN_EXPORT: '/orders/admin/export/',
  },
  PAYMENTS: {
    CREATE_INTENT: '/payments/create-intent/',
    CONFIRM: '/payments/confirm/',
    CANCEL: (id: string) => `/payments/${id}/cancel/`,
    INTENT_DETAIL: (id: string) => `/payments/${id}/`,
    INTENT_STATUS: (id: string) => `/payments/${id}/status/`,
    METHODS: '/payments/methods/',
    METHOD_DETAIL: (id: string) => `/payments/methods/${id}/`,
    METHOD_CARD: '/payments/methods/card/',
    METHOD_MOBILE_MONEY: '/payments/methods/mobile-money/',
    METHOD_BANK_TRANSFER: '/payments/methods/bank-transfer/',
    METHOD_DELETE: (id: string) => `/payments/methods/${id}/`,
    METHOD_SET_DEFAULT: (id: string) => `/payments/methods/${id}/set-default/`,
    METHOD_VERIFY: (id: string) => `/payments/methods/${id}/verify/`,
    MOBILE_MONEY_INITIATE: '/payments/mobile-money/initiate/',
    MOBILE_MONEY_CONFIRM: '/payments/mobile-money/confirm/',
    MOBILE_MONEY_STATUS: (id: string) => `/payments/mobile-money/${id}/status/`,
    BANK_TRANSFER_INITIATE: '/payments/bank-transfer/initiate/',
    BANK_TRANSFER_CONFIRM: '/payments/bank-transfer/confirm/',
    BANK_TRANSFER_DETAILS: (ref: string) => `/payments/bank-transfer/${ref}/`,
    SIMULATE: '/payments/simulate/',
    TRANSACTIONS: '/payments/transactions/',
    TRANSACTION_DETAIL: (id: string) => `/payments/transactions/${id}/`,
    REFUND: (id: string) => `/payments/${id}/refund/`,
    REFUND_STATUS: (id: string) => `/payments/refunds/${id}/status/`,
    WALLET: '/payments/wallet/',
    WALLET_TRANSACTIONS: '/payments/wallet/transactions/',
    WALLET_DEPOSIT: '/payments/wallet/deposit/',
    WALLET_WITHDRAW: '/payments/wallet/withdraw/',
    SUBSCRIPTIONS: '/payments/subscriptions/',
    SUBSCRIPTION_DETAIL: (id: string) => `/payments/subscriptions/${id}/`,
    SUBSCRIPTION_CREATE: '/payments/subscriptions/',
    SUBSCRIPTION_CANCEL: (id: string) => `/payments/subscriptions/${id}/cancel/`,
    SUBSCRIPTION_PLANS: '/payments/subscriptions/plans/',
    PROMOTIONS_VALIDATE: '/payments/promotions/validate/',
    PROMOTIONS_AVAILABLE: '/payments/promotions/available/',
    WEBHOOK: '/payments/webhook/',
    ORDER_METHODS: (id: string) => `/payments/order/${id}/methods/`,
    SUPPORTED_METHODS: '/payments/supported-methods/',
  },
  LOGISTICS: {
    SHIPMENT: (id: string) => `/logistics/shipment/${id}/`,
    SHIPMENT_BY_ID: (id: string) => `/logistics/shipments/${id}/`,
    SHIPMENTS: '/logistics/shipments/',
    TRACKING: (number: string) => `/logistics/tracking/${number}/`,
    TRACKING_HISTORY: (number: string) => `/logistics/tracking/${number}/history/`,
    TRACKING_STATUS: (number: string) => `/logistics/tracking/${number}/status/`,
    TRACKING_MULTIPLE: '/logistics/tracking/multiple/',
    SHIPMENT_STATUS: (id: string) => `/logistics/shipment/${id}/status/`,
    AGENTS: '/logistics/agents/',
    AGENTS_AVAILABLE: '/logistics/agents/available/',
    AGENTS_NEARBY: '/logistics/agents/nearby/',
    AGENT_DETAIL: (id: string) => `/logistics/agents/${id}/`,
    ASSIGN: '/logistics/assign/',
    REASSIGN: (id: string) => `/logistics/assign/${id}/reassign/`,
    ASSIGNMENT: (id: string) => `/logistics/assignments/${id}/`,
    AGENT_DELIVERIES: '/logistics/agent/deliveries/',
    AGENT_ACCEPT: (id: string) => `/logistics/agent/${id}/accept/`,
    AGENT_START: (id: string) => `/logistics/agent/${id}/start/`,
    AGENT_COMPLETE: (id: string) => `/logistics/agent/${id}/complete/`,
    AGENT_FAIL: (id: string) => `/logistics/agent/${id}/fail/`,
    AGENT_LOCATION: '/logistics/agent/location/',
    AGENT_STATS: '/logistics/agent/stats/',
    ZONES: '/logistics/zones/',
    ZONE_DETAIL: (id: string) => `/logistics/zones/${id}/`,
    ZONES_NEARBY: '/logistics/zones/nearby/',
    TIME_SLOTS: '/logistics/time-slots/',
    TIME_SLOTS_AVAILABLE: '/logistics/time-slots/available/',
    ESTIMATE: '/logistics/estimate/',
    ESTIMATE_BULK: '/logistics/estimate/bulk/',
    CARRIERS: '/logistics/carriers/',
    CARRIER_DETAIL: (id: string) => `/logistics/carriers/${id}/`,
    CARRIER_DETECT: '/logistics/carriers/detect/',
    RETURNS: '/logistics/returns/',
    RETURN_DETAIL: (id: string) => `/logistics/returns/${id}/`,
    RETURN_CANCEL: (id: string) => `/logistics/returns/${id}/cancel/`,
    ADMIN_STATISTICS: '/logistics/admin/statistics/',
    ADMIN_PERFORMANCE: '/logistics/admin/performance/',
    ADMIN_HEATMAP: '/logistics/admin/heatmap/',
    ADMIN_AGENTS: (id: string) => `/logistics/admin/agents/${id}/`,
    ADMIN_AGENTS_RATING: (id: string) => `/logistics/admin/agents/${id}/rating/`,
    TRACKING_WEBHOOK: '/logistics/tracking/webhook/',
    PICKUP_POINTS: '/logistics/pickup-points/',
    PICKUP_POINT_DETAIL: (id: string) => `/logistics/pickup-points/${id}/`,
  },
  AI: {
    CHAT: '/ai/chat/',
    CHAT_CONTEXT: '/ai/chat/context/',
    HISTORY: '/ai/history/',
    SESSION: (id: string) => `/ai/session/${id}/`,
    SESSION_ACTIVE: '/ai/session/active/',
    SESSION_START: '/ai/session/start/',
    SESSION_CLOSE: (id: string) => `/ai/session/${id}/close/`,
    TRANSFER: (id: string) => `/ai/transfer/${id}/`,
    STATUS: (id: string) => `/ai/status/${id}/`,
    TOOLS_SEARCH: '/ai/tools/search/',
    TOOLS_RECOMMEND: '/ai/tools/recommend/',
    TOOLS_COMPARE: '/ai/tools/compare/',
    TOOLS_DELIVERY: '/ai/tools/calculate-delivery/',
    TOOLS_AVAILABILITY: '/ai/tools/check-availability/',
    TOOLS_ORDER_STATUS: '/ai/tools/order-status/',
    TOOLS_ADD_TO_CART: '/ai/tools/add-to-cart/',
    TOOLS_GET_CART: '/ai/tools/get-cart/',
    PRODUCT_ADVICE: '/ai/product-advice/',
    PRICE_PREDICTION: '/ai/price-prediction/',
    FAQ: '/ai/faq/',
    FAQ_SEARCH: '/ai/faq/search/',
    ASK: '/ai/ask/',
    SUPPORT_TICKETS: '/ai/support/tickets/',
    SUPPORT_TICKET_CREATE: '/ai/support/tickets/',
    SUPPORT_TICKET_DETAIL: (id: string) => `/ai/support/tickets/${id}/`,
    SUPPORT_TICKET_RESPOND: (id: string) => `/ai/support/tickets/${id}/respond/`,
    SUPPORT_TICKET_CLOSE: (id: string) => `/ai/support/tickets/${id}/close/`,
  },
  SUPPORT: {
    TICKETS: '/support/tickets/',
    TICKET_DETAIL: (id: string) => `/support/tickets/${id}/`,
    TICKET_MESSAGES: (id: string) => `/support/tickets/${id}/messages/`,
    TICKET_REPLY: (id: string) => `/support/tickets/${id}/reply/`,
    TICKET_CLOSE: (id: string) => `/support/tickets/${id}/close/`,
    TICKET_REOPEN: (id: string) => `/support/tickets/${id}/reopen/`,
    TICKET_STATUS: (id: string) => `/support/tickets/${id}/status/`,
    TICKET_ESCALATE: (id: string) => `/support/tickets/${id}/escalate/`,
    TICKET_HISTORY: (id: string) => `/support/tickets/${id}/history/`,
    TICKET_SURVEY: (id: string) => `/support/tickets/${id}/survey/`,
    TICKET_TAGS: (id: string) => `/support/tickets/${id}/tags/`,
    TICKET_TAG_DELETE: (id: string, tag: string) => `/support/tickets/${id}/tags/${tag}/`,
    TICKET_NOTES: (id: string) => `/support/tickets/${id}/notes/`,
    TICKET_AUTO_SUGGEST: (id: string) => `/support/tickets/${id}/auto-suggest/`,
    SATISFACTION_STATS: '/support/satisfaction/stats/',
    SATISFACTION_SURVEY: (id: string) => `/support/satisfaction/${id}/`,
    FAQS: '/support/faqs/',
    FAQ_DETAIL: (id: string) => `/support/faqs/${id}/`,
    FAQ_CATEGORIES: '/support/faqs/categories/',
    FAQ_SEARCH: '/support/faqs/search/',
    FAQ_HELPFUL: (id: string) => `/support/faqs/${id}/helpful/`,
    FAQ_POPULAR: '/support/faqs/popular/',
    FAQ_CATEGORY: (category: string) => `/support/faqs/category/${category}/`,
    KNOWLEDGE_BASE: '/support/knowledge-base/',
    KNOWLEDGE_BASE_DETAIL: (id: string) => `/support/knowledge-base/${id}/`,
    KNOWLEDGE_BASE_SEARCH: '/support/knowledge-base/search/',
    KNOWLEDGE_BASE_HELPFUL: (id: string) => `/support/knowledge-base/${id}/helpful/`,
    KNOWLEDGE_BASE_POPULAR: '/support/knowledge-base/popular/',
    ADMIN_TICKETS: '/support/admin/tickets/',
    ADMIN_TICKET_ASSIGN: (id: string) => `/support/admin/tickets/${id}/assign/`,
    ADMIN_TICKET_STATUS: (id: string) => `/support/admin/tickets/${id}/status/`,
    ADMIN_TICKET_PRIORITY: (id: string) => `/support/admin/tickets/${id}/priority/`,
    ADMIN_TICKET_CATEGORY: (id: string) => `/support/admin/tickets/${id}/category/`,
    ADMIN_STATISTICS: '/support/admin/statistics/',
    ADMIN_ADVISORS: '/support/admin/advisors/',
    ADMIN_ADVISOR: (id: string) => `/support/admin/advisors/${id}/`,
    ADMIN_ADVISOR_STATS: (id: string) => `/support/admin/advisors/${id}/stats/`,
    ADMIN_ADVISOR_TICKETS: (id: string) => `/support/admin/advisors/${id}/tickets/`,
    ADMIN_FAQS: '/support/admin/faqs/',
    ADMIN_FAQ_DETAIL: (id: string) => `/support/admin/faqs/${id}/`,
    ADMIN_FAQ_REORDER: '/support/admin/faqs/reorder/',
    ADMIN_FAQ_IMPORT: '/support/admin/faqs/import/',
    ADMIN_FAQ_EXPORT: '/support/admin/faqs/export/',
    ADMIN_KNOWLEDGE_BASE: '/support/admin/knowledge-base/',
    ADMIN_KNOWLEDGE_BASE_DETAIL: (id: string) => `/support/admin/knowledge-base/${id}/`,
    ADMIN_EXPORT: '/support/admin/export/',
    ADMIN_EXPORT_SATISFACTION: '/support/admin/export/satisfaction/',
    TAGS: '/support/tags/',
    AUTO_RESPONSES: '/support/auto-responses/',
    ATTACHMENTS_DOWNLOAD: (id: string) => `/support/attachments/${id}/download/`,
    ATTACHMENTS_DELETE: (id: string) => `/support/attachments/${id}/`,
    ESCALATION_LEVELS: '/support/escalation/levels/',
    ESCALATION_HISTORY: (id: string) => `/support/tickets/${id}/escalation-history/`,
  },
  NOTIFICATIONS: {
    LIST: '/notifications/',
    UNREAD_COUNT: '/notifications/unread/count/',
    READ: (id: string) => `/notifications/${id}/read/`,
    READ_ALL: '/notifications/mark-all-read/',
    READ_MULTIPLE: '/notifications/mark-read/',
    DELETE: (id: string) => `/notifications/${id}/`,
    DELETE_ALL: '/notifications/',
    DELETE_READ: '/notifications/read/',
    PREFERENCES: '/notifications/preferences/',
    PREFERENCES_CHANNEL: '/notifications/preferences/channel/',
    PUSH_REGISTER: '/notifications/push/register/',
    PUSH_UNREGISTER: '/notifications/push/unregister/',
    PUSH_SUBSCRIPTIONS: '/notifications/push/subscriptions/',
    TEST: '/notifications/test/',
    BROADCAST: '/notifications/broadcast/',
    EMAIL_SUBSCRIBE: '/notifications/email/subscribe/',
    EMAIL_UNSUBSCRIBE: '/notifications/email/unsubscribe/',
    EMAIL_SUBSCRIPTIONS: '/notifications/email/subscriptions/',
    SMS_SUBSCRIBE: '/notifications/sms/subscribe/',
    SMS_UNSUBSCRIBE: '/notifications/sms/unsubscribe/',
    SETTINGS: '/notifications/settings/',
    TYPES: '/notifications/types/',
    TEMPLATES: '/notifications/templates/',
  },
  ANALYTICS: {
    PAGE_VIEW: '/analytics/page-view/',
    PAGE_VIEWS: '/analytics/page-views/',
    PAGE_VIEWS_STATS: '/analytics/page-views/stats/',
    ACTION: '/analytics/action/',
    USER_SESSIONS: (id: string) => `/analytics/user/${id}/sessions/`,
    USER_ACTIONS: (id: string) => `/analytics/user/${id}/actions/`,
    EVENT: '/analytics/event/',
    EVENTS: '/analytics/events/',
    EVENTS_STATS: '/analytics/events/stats/',
    FUNNEL: (id: string) => `/analytics/funnels/${id}/`,
    CONVERSION_RATE: '/analytics/conversion-rate/',
    RETENTION: '/analytics/retention/',
    COHORT: '/analytics/cohort/',
    REVENUE: '/analytics/revenue/',
    REVENUE_PRODUCT: '/analytics/revenue/product/',
    PRODUCT: (id: string) => `/analytics/product/${id}/`,
    TOP_PRODUCTS: '/analytics/top-products/',
    USERS: '/analytics/users/',
    PERFORMANCE: '/analytics/performance/',
    SYSTEM: '/analytics/system/',
    AB_TESTS: '/analytics/ab-tests/',
    AB_TEST_DETAIL: (id: string) => `/analytics/ab-tests/${id}/`,
    AB_TEST_RESULTS: (id: string) => `/analytics/ab-tests/${id}/results/`,
    REALTIME: '/analytics/realtime/',
    LIVE_VISITORS: '/analytics/live-visitors/',
    GEOLOCATION: '/analytics/geolocation/',
    DEVICES: '/analytics/devices/',
    EXPORT: '/analytics/export/',
    EXPORTS: '/analytics/exports/',
    EXPORT_DETAIL: (id: string) => `/analytics/exports/${id}/`,
    EXPORT_DOWNLOAD: (id: string) => `/analytics/exports/${id}/download/`,
    DASHBOARD: '/analytics/dashboard/',
  },
} as const;

// ============ STORAGE KEYS ============

export const STORAGE_KEYS = {
  TOKEN: 'token',
  REFRESH_TOKEN: 'refreshToken',
  USER: 'user',
  CART: 'cart',
  CART_ID: 'cartId',
  THEME: 'theme',
  LANGUAGE: 'language',
  SESSION_ID: 'analytics_session_id',
  PREFERENCES: 'preferences',
  RECENT_PRODUCTS: 'recent_products',
  SEARCH_HISTORY: 'search_history',
  WISHLIST: 'wishlist',
} as const;

// ============ PAGINATION ============

export const DEFAULT_PAGINATION = {
  PAGE: 1,
  LIMIT: 20,
  MAX_LIMIT: 100,
} as const;

// ============ COUNTRIES ============

export const COUNTRIES = [
  { code: 'SN', name: 'Sénégal', dialCode: '+221', currency: 'XOF' },
  { code: 'CI', name: 'Côte d\'Ivoire', dialCode: '+225', currency: 'XOF' },
  { code: 'ML', name: 'Mali', dialCode: '+223', currency: 'XOF' },
  { code: 'GN', name: 'Guinée', dialCode: '+224', currency: 'GNF' },
  { code: 'GM', name: 'Gambie', dialCode: '+220', currency: 'GMD' },
  { code: 'BF', name: 'Burkina Faso', dialCode: '+226', currency: 'XOF' },
  { code: 'BJ', name: 'Bénin', dialCode: '+229', currency: 'XOF' },
  { code: 'TG', name: 'Togo', dialCode: '+228', currency: 'XOF' },
  { code: 'GH', name: 'Ghana', dialCode: '+233', currency: 'GHS' },
  { code: 'NG', name: 'Nigeria', dialCode: '+234', currency: 'NGN' },
] as const;

// ============ CURRENCIES ============

export const CURRENCIES = {
  XOF: { code: 'XOF', symbol: 'CFA', name: 'Franc CFA' },
  EUR: { code: 'EUR', symbol: '€', name: 'Euro' },
  USD: { code: 'USD', symbol: '$', name: 'Dollar US' },
  GBP: { code: 'GBP', symbol: '£', name: 'Livre Sterling' },
  GNF: { code: 'GNF', symbol: 'FG', name: 'Franc Guinéen' },
  GMD: { code: 'GMD', symbol: 'D', name: 'Dalasi' },
  GHS: { code: 'GHS', symbol: '₵', name: 'Cedi' },
  NGN: { code: 'NGN', symbol: '₦', name: 'Naira' },
} as const;

// ============ PAYMENT PROVIDERS ============

export const PAYMENT_PROVIDERS = {
  MOBILE_MONEY: ['orange', 'wave', 'free', 'expresso'] as const,
  CARD: ['visa', 'mastercard', 'amex'] as const,
  BANK: ['ecobank', 'sgb', 'cba', 'bicis'] as const,
} as const;

// ============ DELIVERY ZONES ============

export const DELIVERY_ZONES = {
  DAKAR: 'dakar',
  THIES: 'thies',
  SAINT_LOUIS: 'saint_louis',
  TOUBA: 'touba',
  ZIGUINCHOR: 'ziguinchor',
  KAOLACK: 'kaolack',
  MBOUR: 'mbour',
  RUFISQUE: 'rufisque',
  OTHER: 'other',
} as const;

// ============ FILE CONSTRAINTS ============

export const FILE_CONSTRAINTS = {
  MAX_SIZE: 5 * 1024 * 1024, // 5MB
  ALLOWED_IMAGES: ['image/jpeg', 'image/png', 'image/gif', 'image/webp'],
  ALLOWED_DOCUMENTS: ['application/pdf', 'application/msword', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
  ALLOWED_VIDEOS: ['video/mp4', 'video/webm', 'video/ogg'],
} as const;

// ============ REGEX PATTERNS ============

export const REGEX = {
  EMAIL: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
  PHONE: /^(\+?[0-9]{1,3})?[0-9]{9,12}$/,
  URL: /^(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w \.-]*)*\/?$/,
  SLUG: /^[a-z0-9]+(?:-[a-z0-9]+)*$/,
  PASSWORD: /^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9])/,
  CARD_NUMBER: /^[0-9]{16}$/,
  CVC: /^[0-9]{3,4}$/,
  POSTAL_CODE: /^[0-9]{5}$/,
} as const;

// ============ DATE FORMATS ============

export const DATE_FORMATS = {
  DISPLAY: 'dd MMMM yyyy',
  DISPLAY_TIME: 'dd MMMM yyyy HH:mm',
  TIME: 'HH:mm',
  API: 'yyyy-MM-dd',
  API_DATETIME: "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'",
} as const;

// ============ MESSAGES ============

export const MESSAGES = {
  AUTH: {
    LOGIN_SUCCESS: 'Connexion réussie',
    LOGIN_ERROR: 'Email ou mot de passe incorrect',
    REGISTER_SUCCESS: 'Inscription réussie',
    REGISTER_ERROR: 'Erreur lors de l\'inscription',
    LOGOUT_SUCCESS: 'Déconnexion réussie',
    LOGOUT_ERROR: 'Erreur lors de la déconnexion',
    PASSWORD_RESET_SENT: 'Email de réinitialisation envoyé',
    PASSWORD_RESET_SUCCESS: 'Mot de passe réinitialisé avec succès',
    PASSWORD_RESET_ERROR: 'Erreur lors de la réinitialisation',
    EMAIL_VERIFICATION_SENT: 'Email de vérification envoyé',
    EMAIL_VERIFICATION_SUCCESS: 'Email vérifié avec succès',
    EMAIL_VERIFICATION_ERROR: 'Erreur lors de la vérification',
  },
  CART: {
    ADD_SUCCESS: 'Produit ajouté au panier',
    ADD_ERROR: 'Erreur lors de l\'ajout au panier',
    REMOVE_SUCCESS: 'Produit retiré du panier',
    REMOVE_ERROR: 'Erreur lors du retrait du panier',
    UPDATE_SUCCESS: 'Panier mis à jour',
    UPDATE_ERROR: 'Erreur lors de la mise à jour',
    CLEAR_SUCCESS: 'Panier vidé',
    CLEAR_ERROR: 'Erreur lors du vidage du panier',
    COUPON_SUCCESS: 'Coupon appliqué avec succès',
    COUPON_ERROR: 'Coupon invalide',
  },
  ORDER: {
    CREATE_SUCCESS: 'Commande créée avec succès',
    CREATE_ERROR: 'Erreur lors de la création de la commande',
    CANCEL_SUCCESS: 'Commande annulée',
    CANCEL_ERROR: 'Erreur lors de l\'annulation',
    UPDATE_SUCCESS: 'Commande mise à jour',
    UPDATE_ERROR: 'Erreur lors de la mise à jour',
  },
  PAYMENT: {
    SUCCESS: 'Paiement effectué avec succès',
    ERROR: 'Erreur lors du paiement',
    PENDING: 'Paiement en cours de traitement',
  },
  GENERAL: {
    LOADING: 'Chargement en cours...',
    ERROR: 'Une erreur est survenue',
    SUCCESS: 'Opération réussie',
    CONFIRM: 'Êtes-vous sûr de vouloir continuer ?',
    SAVE_SUCCESS: 'Enregistré avec succès',
    SAVE_ERROR: 'Erreur lors de l\'enregistrement',
    DELETE_SUCCESS: 'Supprimé avec succès',
    DELETE_ERROR: 'Erreur lors de la suppression',
  },
} as const;

// ============ EXPORT ============

export default {
  API_ENDPOINTS,
  STORAGE_KEYS,
  DEFAULT_PAGINATION,
  COUNTRIES,
  CURRENCIES,
  PAYMENT_PROVIDERS,
  DELIVERY_ZONES,
  FILE_CONSTRAINTS,
  REGEX,
  DATE_FORMATS,
  MESSAGES,
};